server {
    listen 80;
    server_name localhost;

    location /etudiant/ {
        proxy_pass http://etudiant-frontend:3000;
    }
    location /doctorant/ {
        proxy_pass http://doctorant-frontend:3000;
    }
    location /admin/ {
        proxy_pass http://admin-frontend:3000;
    }
}
